# Generated by gallery/generate.py; do not edit.
function trophymanager_gallery:clear
# stock-control: stone stock rendering control
setblock 176 100 175 minecraft:stone
function trophymanager_gallery:verify
