# Generated by gallery/generate.py; do not edit.
function trophymanager_gallery:clear
# slab-control: smooth-stone slab stock control
setblock 164 100 168 minecraft:smooth_stone_slab[type=bottom,waterlogged=false]
# diamond-smooth: diamond block trophy on smooth stone
setblock 166 100 168 trophymanager:trophy[facing=south,waterlogged=false]
data merge block 166 100 168 {TrophyData:{TrophyType:"item",TrophyItem:{id:"minecraft:diamond_block",count:1},OffsetY:0.5d,RotX:0.0f,Scale:0.5f,BaseBlock:"minecraft:smooth_stone_slab",Name:"Diamond"}}
# gold-sandstone: gold block trophy on cut sandstone
setblock 168 100 168 trophymanager:trophy[facing=east,waterlogged=false]
data merge block 168 100 168 {TrophyData:{TrophyType:"item",TrophyItem:{id:"minecraft:gold_block",count:1},OffsetY:0.5d,RotX:0.0f,Scale:0.5f,BaseBlock:"minecraft:cut_sandstone_slab",Name:"Gold"}}
# emerald-oak: scaled emerald block trophy on oak
setblock 170 100 168 trophymanager:trophy[facing=north,waterlogged=false]
data merge block 170 100 168 {TrophyData:{TrophyType:"item",TrophyItem:{id:"minecraft:emerald_block",count:1},OffsetY:0.55d,RotX:0.0f,Scale:0.65f,BaseBlock:"minecraft:oak_slab",Name:"Emerald"}}
# redstone-deepslate: small redstone block trophy on deepslate tile
setblock 172 100 168 trophymanager:trophy[facing=west,waterlogged=false]
data merge block 172 100 168 {TrophyData:{TrophyType:"item",TrophyItem:{id:"minecraft:redstone_block",count:1},OffsetY:0.6d,RotX:0.0f,Scale:0.4f,BaseBlock:"minecraft:deepslate_tile_slab",Name:"Redstone"}}
# creeper-entity: creeper entity trophy on brick slab
setblock 174 100 168 trophymanager:trophy[facing=north,waterlogged=false]
data merge block 174 100 168 {TrophyData:{TrophyType:"entity",TrophyEntity:{entityType:"minecraft:creeper"},OffsetY:0.5d,RotX:0.0f,Scale:0.5f,BaseBlock:"minecraft:brick_slab",Name:"Creeper"}}
function trophymanager_gallery:verify
