# Generated by gallery/generate.py; do not edit.
execute unless block 164 100 168 minecraft:smooth_stone_slab[type=bottom,waterlogged=false] run tellraw @a {"text":"gallery mismatch: slab-control","color":"red"}
execute unless block 166 100 168 trophymanager:trophy[facing=south,waterlogged=false] run tellraw @a {"text":"gallery mismatch: diamond-smooth","color":"red"}
execute unless data block 166 100 168 {TrophyData:{TrophyType:"item",TrophyItem:{id:"minecraft:diamond_block",count:1},OffsetY:0.5d,RotX:0.0f,Scale:0.5f,BaseBlock:"minecraft:smooth_stone_slab",Name:"Diamond"}} run tellraw @a {"text":"gallery trophy-data mismatch: diamond-smooth","color":"red"}
execute unless block 168 100 168 trophymanager:trophy[facing=east,waterlogged=false] run tellraw @a {"text":"gallery mismatch: gold-sandstone","color":"red"}
execute unless data block 168 100 168 {TrophyData:{TrophyType:"item",TrophyItem:{id:"minecraft:gold_block",count:1},OffsetY:0.5d,RotX:0.0f,Scale:0.5f,BaseBlock:"minecraft:cut_sandstone_slab",Name:"Gold"}} run tellraw @a {"text":"gallery trophy-data mismatch: gold-sandstone","color":"red"}
execute unless block 170 100 168 trophymanager:trophy[facing=north,waterlogged=false] run tellraw @a {"text":"gallery mismatch: emerald-oak","color":"red"}
execute unless data block 170 100 168 {TrophyData:{TrophyType:"item",TrophyItem:{id:"minecraft:emerald_block",count:1},OffsetY:0.55d,RotX:0.0f,Scale:0.65f,BaseBlock:"minecraft:oak_slab",Name:"Emerald"}} run tellraw @a {"text":"gallery trophy-data mismatch: emerald-oak","color":"red"}
execute unless block 172 100 168 trophymanager:trophy[facing=west,waterlogged=false] run tellraw @a {"text":"gallery mismatch: redstone-deepslate","color":"red"}
execute unless data block 172 100 168 {TrophyData:{TrophyType:"item",TrophyItem:{id:"minecraft:redstone_block",count:1},OffsetY:0.6d,RotX:0.0f,Scale:0.4f,BaseBlock:"minecraft:deepslate_tile_slab",Name:"Redstone"}} run tellraw @a {"text":"gallery trophy-data mismatch: redstone-deepslate","color":"red"}
execute unless block 174 100 168 trophymanager:trophy[facing=north,waterlogged=false] run tellraw @a {"text":"gallery mismatch: entity-fallback","color":"red"}
execute unless data block 174 100 168 {TrophyData:{TrophyType:"entity",TrophyEntity:{entityType:"minecraft:creeper"},OffsetY:0.5d,RotX:0.0f,Scale:0.5f,BaseBlock:"minecraft:brick_slab",Name:"Creeper"}} run tellraw @a {"text":"gallery trophy-data mismatch: entity-fallback","color":"red"}
tellraw @a {"text":"Trophy Manager gallery verification finished; inspect any mismatch above","color":"aqua"}
